version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: teamBuilderDB
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: teamBuilderUser
      MONGO_INITDB_ROOT_PASSWORD: teamBuilderPassword
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command: mongod --auth

volumes:
  mongo_data:
