spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: teamBuilderDB
      username: teamBuilderUser
      password: teamBuilderPassword
      authentication-database: admin
  application:
    name: TeamBuilder
