# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://teamBuilderUser:teamBuilderPassword@localhost:27017/teamBuilderDB?authSource=admin
spring.data.mongodb.database=teamBuilderDB

# Application Name
spring.application.name=TeamBuilder

# Static images
spring.web.resources.static-locations=file:../images/
spring.mvc.static-path-pattern=/images/**

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=INFO
